-- Databricks notebook source
-- MAGIC %md
-- MAGIC ## Quick Start & データパイプライン作成

-- COMMAND ----------

-- MAGIC %python
-- MAGIC displayHTML("""
-- MAGIC <style>
-- MAGIC   .slide-container {
-- MAGIC     font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
-- MAGIC     max-width: 900px;
-- MAGIC     margin: 0 auto;
-- MAGIC     padding: 10px 20px 20px 20px;
-- MAGIC     position: relative;
-- MAGIC   }
-- MAGIC   .slide {
-- MAGIC     background: rgb(249, 247, 244);
-- MAGIC     color: rgb(27, 49, 57);
-- MAGIC     padding: 20px 20px;
-- MAGIC     margin: 12px 0;
-- MAGIC     border-radius: 10px;
-- MAGIC     box-shadow: 0 10px 30px rgba(0,0,0,0.15);
-- MAGIC     height: 420px; /* 高さを固定し、内容が見やすいサイズに調整 */
-- MAGIC     display: none;
-- MAGIC     overflow-y: auto;
-- MAGIC   }
-- MAGIC   .slide.active {
-- MAGIC     display: block;
-- MAGIC   }
-- MAGIC   .slide h3 {
-- MAGIC     font-size: 1.3em;
-- MAGIC     margin-bottom: 15px;
-- MAGIC     margin-top: 0;
-- MAGIC     border-bottom: 2px solid rgb(255, 95, 70);
-- MAGIC     padding-bottom: 6px;
-- MAGIC     color: rgb(27, 49, 57);
-- MAGIC   }
-- MAGIC   .slide ul {
-- MAGIC     font-size: 1em;
-- MAGIC     line-height: 1.5;
-- MAGIC     list-style: none;
-- MAGIC     padding-left: 0;
-- MAGIC     margin: 0;
-- MAGIC   }
-- MAGIC   .slide ul li {
-- MAGIC     margin: 8px 0;
-- MAGIC     padding-left: 22px;
-- MAGIC     position: relative;
-- MAGIC     color: rgb(27, 49, 57);
-- MAGIC   }
-- MAGIC   .slide ul li:before {
-- MAGIC     content: '▸';
-- MAGIC     position: absolute;
-- MAGIC     left: 0;
-- MAGIC     color: rgb(255, 95, 70);
-- MAGIC     font-weight: bold;
-- MAGIC   }
-- MAGIC   .slide ul ul {
-- MAGIC     font-size: 0.9em;
-- MAGIC     margin-top: 4px;
-- MAGIC   }
-- MAGIC   .slide ul ul li {
-- MAGIC     color: rgb(90, 111, 119);
-- MAGIC     margin: 4px 0;
-- MAGIC   }
-- MAGIC   .slide ul ul li:before {
-- MAGIC     content: '•';
-- MAGIC     color: rgb(90, 111, 119);
-- MAGIC   }
-- MAGIC   .slide strong {
-- MAGIC     color: rgb(255, 95, 70);
-- MAGIC     font-weight: 600;
-- MAGIC   }
-- MAGIC   .slide code {
-- MAGIC     background: rgba(255, 95, 70, 0.1);
-- MAGIC     color: rgb(255, 95, 70);
-- MAGIC     padding: 2px 8px;
-- MAGIC     border-radius: 4px;
-- MAGIC     font-family: 'Courier New', monospace;
-- MAGIC   }
-- MAGIC   .slide-number {
-- MAGIC     text-align: right;
-- MAGIC     opacity: 0.6;
-- MAGIC     font-size: 0.85em;
-- MAGIC     margin-top: 10px;
-- MAGIC     color: rgb(90, 111, 119);
-- MAGIC   }
-- MAGIC   .navigation {
-- MAGIC     text-align: center;
-- MAGIC     margin: 18px 0;
-- MAGIC   }
-- MAGIC   .nav-button {
-- MAGIC     background: rgb(255, 95, 70);
-- MAGIC     color: white;
-- MAGIC     border: none;
-- MAGIC     padding: 7px 18px;
-- MAGIC     margin: 0 6px;
-- MAGIC     border-radius: 6px;
-- MAGIC     font-size: 0.95em;
-- MAGIC     cursor: pointer;
-- MAGIC     box-shadow: 0 2px 8px rgba(255, 95, 70, 0.2);
-- MAGIC     transition: all 0.3s ease;
-- MAGIC   }
-- MAGIC   .nav-button:hover {
-- MAGIC     transform: translateY(-1px);
-- MAGIC     box-shadow: 0 4px 12px rgba(255, 95, 70, 0.25);
-- MAGIC     background: rgb(255, 110, 85);
-- MAGIC   }
-- MAGIC   .nav-button:disabled {
-- MAGIC     opacity: 0.4;
-- MAGIC     cursor: not-allowed;
-- MAGIC     transform: none;
-- MAGIC     background: rgb(90, 111, 119);
-- MAGIC   }
-- MAGIC   .progress-bar {
-- MAGIC     width: 100%;
-- MAGIC     height: 6px;
-- MAGIC     background: rgb(249, 247, 244);
-- MAGIC     border: 1px solid rgb(90, 111, 119);
-- MAGIC     border-radius: 4px;
-- MAGIC     margin: 10px 0 16px 0;
-- MAGIC     overflow: hidden;
-- MAGIC   }
-- MAGIC   .progress-fill {
-- MAGIC     height: 100%;
-- MAGIC     background: rgb(255, 95, 70);
-- MAGIC     transition: width 0.3s ease;
-- MAGIC   }
-- MAGIC </style>
-- MAGIC
-- MAGIC <div class="slide-container">
-- MAGIC   <div class="progress-bar">
-- MAGIC     <div class="progress-fill" id="progressFill" style="width: 33.3%;"></div>
-- MAGIC   </div>
-- MAGIC
-- MAGIC   <div class="slide active" data-slide="1">
-- MAGIC     <h3>Databricks Notebookの特徴</h3>
-- MAGIC     <ul>
-- MAGIC       <li><strong>複数言語サポート</strong>
-- MAGIC         <ul>
-- MAGIC           <li>Python、SQL、Scala、Rを1つのノートブック内で利用可能</li>
-- MAGIC           <li>セルごとに言語を切り替えられる</li>
-- MAGIC         </ul>
-- MAGIC       </li>
-- MAGIC       <li><strong>リアルタイムコラボレーション</strong>
-- MAGIC         <ul>
-- MAGIC           <li>複数人で同時編集・コメントが可能</li>
-- MAGIC         </ul>
-- MAGIC       </li>
-- MAGIC       <li><strong>バージョン管理</strong>
-- MAGIC         <ul>
-- MAGIC           <li>自動で変更履歴を保存</li>
-- MAGIC           <li>過去の状態に簡単に戻せる</li>
-- MAGIC         </ul>
-- MAGIC       </li>
-- MAGIC       <li><strong>ジョブ・自動化</strong>
-- MAGIC         <ul>
-- MAGIC           <li>ノートブックをスケジュール実行</li>
-- MAGIC           <li>パラメータを渡して柔軟なワークフロー構築</li>
-- MAGIC         </ul>
-- MAGIC       </li>
-- MAGIC       <li><strong>AI支援</strong>
-- MAGIC         <ul>
-- MAGIC           <li>AI Assistantによるコード生成・補完・エラー修正</li>
-- MAGIC         </ul>
-- MAGIC       </li>
-- MAGIC       <li><strong>Databricks連携</strong>
-- MAGIC         <ul>
-- MAGIC           <li>データガバナンス・カタログ管理: <strong>Unity Catalog</strong> による一元管理</li>
-- MAGIC           <li>機械学習ライフサイクル管理: <strong>MLflow</strong> との統合</li>
-- MAGIC         </ul>
-- MAGIC       </li>
-- MAGIC     </ul>
-- MAGIC     <div class="slide-number">スライド 1/2</div>
-- MAGIC   </div>
-- MAGIC
-- MAGIC   <div class="slide" data-slide="2">
-- MAGIC     <h3>こちらのノートブック内容</h3>
-- MAGIC     <ul>
-- MAGIC       <li>Notebook の使い方</li>
-- MAGIC       <li>Unity Catalogによる本日利用するデータの確認</li>
-- MAGIC       <li>AI Assistantを利用したデータパイプライン構築</li>
-- MAGIC       <li>CSVファイルの読み込み</li>
-- MAGIC       <li>作成されたパイプラインの確認</li>
-- MAGIC     </ul>
-- MAGIC     <div style="margin-top: 20px; padding: 10px; background: rgba(255, 95, 70, 0.1); border-radius: 8px; border-left: 4px solid rgb(255, 95, 70);">
-- MAGIC       <strong style="font-size: 1.05em; display: block; margin-bottom: 8px;">✨ こちらのノートブックのゴール</strong>
-- MAGIC       <ul style="margin-top: 6px;">
-- MAGIC         <li>Databricksの基本操作を体験</li>
-- MAGIC         <li>データパイプライン構築の流れを理解</li>
-- MAGIC         <li>AI支援による効率的な分析を実感</li>
-- MAGIC       </ul>
-- MAGIC     </div>
-- MAGIC     <div class="slide-number">スライド 2/2</div>
-- MAGIC   </div>
-- MAGIC
-- MAGIC   <div class="navigation">
-- MAGIC     <button class="nav-button" id="prevBtn" onclick="changeSlide(-1)">◀ 前へ</button>
-- MAGIC     <button class="nav-button" id="nextBtn" onclick="changeSlide(1)">次へ ▶</button>
-- MAGIC   </div>
-- MAGIC </div>
-- MAGIC
-- MAGIC <script>
-- MAGIC let currentSlide = 1;
-- MAGIC const totalSlides = 2;
-- MAGIC
-- MAGIC function showSlide(n) {
-- MAGIC   const slides = document.querySelectorAll('.slide');
-- MAGIC   const prevBtn = document.getElementById('prevBtn');
-- MAGIC   const nextBtn = document.getElementById('nextBtn');
-- MAGIC   const progressFill = document.getElementById('progressFill');
-- MAGIC   
-- MAGIC   if (n > totalSlides) currentSlide = totalSlides;
-- MAGIC   if (n < 1) currentSlide = 1;
-- MAGIC   
-- MAGIC   slides.forEach(slide => slide.classList.remove('active'));
-- MAGIC   slides[currentSlide - 1].classList.add('active');
-- MAGIC   
-- MAGIC   prevBtn.disabled = (currentSlide === 1);
-- MAGIC   nextBtn.disabled = (currentSlide === totalSlides);
-- MAGIC   
-- MAGIC   const progress = (currentSlide / totalSlides) * 100;
-- MAGIC   progressFill.style.width = progress + '%';
-- MAGIC }
-- MAGIC
-- MAGIC function changeSlide(direction) {
-- MAGIC   currentSlide += direction;
-- MAGIC   showSlide(currentSlide);
-- MAGIC }
-- MAGIC
-- MAGIC showSlide(currentSlide);
-- MAGIC </script>
-- MAGIC """)

-- COMMAND ----------

-- DBTITLE 1,ハンズオン環境セットアップ
-- MAGIC %run ../0_userenv

-- COMMAND ----------

-- MAGIC %md
-- MAGIC
-- MAGIC ## 1. silver_inquiry テーブルの作成
-- MAGIC
-- MAGIC handson_catalog.handson_db にある bronze_inquiry_historyと bronze_user をuser_idをキーとして結合し、silver_inquiry テーブルを作成。 その際に、保存場所はhandson_catalog.databricks。またuser_idカラムは重複しないように一つだけ残すようにする。また作成するテーブルはすでにある場合は上書きする。最後に作成したテーブルを表示
-- MAGIC

-- COMMAND ----------

-- MAGIC %md
-- MAGIC
-- MAGIC ## 2. CSVファイルから、bronze_sales テーブルを作成
-- MAGIC
-- MAGIC UnityCatalog Volumes上のhandson_catalog.handson_db.handson_volume にある sales_mapping.csv ファイルを読み込み、handson_catalog.databricksに bronze_salesテーブルとして保存。その際にread_filesを使い、headerあり、カラムのスキーマも推測する。また作成するテーブルはすでにある場合は上書きする。最後に作成したテーブルを表示。 (パスは/Volumesとする)

-- COMMAND ----------

-- MAGIC %md
-- MAGIC
-- MAGIC ## 3. silver_inquiry_sales テーブルを作成
-- MAGIC
-- MAGIC handson_catalog.databricks にある silver_inquiryと bronze_sales をcs_rep と sales_rep_id をキーとして結合し、silver_inquiry_sales テーブルを作成。 保存場所はhandson_catalog.databricks。またcs_repカラムのみ残して、sales_rep_idは削除する。_rescued_dataカラムは不要。また作成するテーブルはすでにある場合は上書きする。最後に作成したテーブルを表示
